name: Build and Test
on:
  push:
    branches: [ master ]
  pull_request:
    type: [ synchronize ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - runner: "macos-latest"
            build-script: "hix build .#dhall-secret:exe:dhall-secret"
          - runner: "ubuntu-latest"
            build-script: "hix build .#x86_64-unknown-linux-musl:dhall-secret:exe:dhall-secret"
    name: build on ${{ matrix.os.runner }}
    runs-on: ${{ matrix.os.runner }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.iog.io https://hydra.iohk.io https://cache.nixos.org/
    - uses: cachix/cachix-action@v10
      with:
        name: jcouyang
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-env -iA hix -f https://github.com/input-output-hk/haskell.nix/tarball/0.0.58
    - name: Test
      run: hix run .#dhall-secret:test:dhall-secret-test
    - name: Static Binary
      run: ${{matrix.os.build-script}}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.os.runner}}-binary
        path: ./result/bin/dhall-secret
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'publish skip') && (github.ref == 'refs/heads/master')"
    needs:
      - build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: dhall-lang/setup-dhall@v4
    - uses: actions/download-artifact@v2
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.iog.io https://hydra.iohk.io https://cache.nixos.org/
    - uses: cachix/cachix-action@v10
      with:
        name: jcouyang
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: tag release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HACKAGE_PASS: ${{ secrets.HACKAGE_PASS }}
      run: |
        VERSION=$(dhall text < ./version.dhall)
        echo publishing $VERSION lib...
        env VER=$VERSION nix-shell -p gnused --run 'sed -i "s/0.1.0.0/${VER}/" ./package.yaml'
        echo -e "oyanglulu\n${HACKAGE_PASS}\nn\n" | stack upload . --candidate
        echo publishing $VERSION binary...
        mv ubuntu-latest-binary/dhall-secret dhall-secret-x86_64-linux
        mv macos-10.15-binary/dhall-secret dhall-secret-x86_64-macOS
        gh release create "v$VERSION" ./dhall-secret-x86_64-linux ./dhall-secret-x86_64-macOS
